### ISSUE TITLE
ImportError on one of the internationalstrings modules when trying to run analysis 

### ISSUE THREAD

**Issue by andreakb** [exponential-decay/droid-siegfried-sqlite-analysis-engine#41]
Hi,

I just tried to run the analysis on a Siegfried CSV export file, and I got the following error message: 

akb@debian:~$ python git-repos/droid-siegfried-sqlite-analysis-engine-master/droidsqliteanalysis.py --export ResurectionMen.csv 
Traceback (most recent call last):
  File "git-repos/droid-siegfried-sqlite-analysis-engine-master/droidsqliteanalysis.py", line 10, in <module>
    from libs.DroidAnalysisClass import DROIDAnalysis
  File "/home/akb/git-repos/droid-siegfried-sqlite-analysis-engine-master/libs/DroidAnalysisClass.py", line 7, in <module>
    import MsoftFnameAnalysis
  File "/home/akb/git-repos/droid-siegfried-sqlite-analysis-engine-master/libs/MsoftFnameAnalysis.py", line 8, in <module>
    from internationalstrings import AnalysisStringsEN as IN_EN
ImportError: No module named internationalstrings

It looks to me like the MsoftFnameAnalysis.py module is trying to import a module that doesn't exist in the repo?

Thank you!

**Comment by andreakb** [comment]
NVM! This was my fault. I'll deleting this now. Sorry!!!

**Comment by ross-spencer** [comment]
I got all excited I had something to do there for a second!! 

(Hope the report works well for you! - I'm considering improvements, like packaging it properly for download but I'm not sure there are many folks using it atm)

**Comment by andreakb** [comment]
Hahaaa, Sorry! the other thing I'm trying to figure out here is: I have an export from SF, but when I try to run the report, the message says Unknown export type. I have a SF in csv format with sha1 checksums... should I be exporting to something else? No rush! Thank you!

**Comment by ross-spencer** [comment]
Oh yeah, that's a compatibility thing. I should document that better, but it doesn't work with the SF CSV output because SF wasn't quite outputting easy to manage 2D data, so I use SF's YAML, and then DROID's CSV. To get DROID's CSV from SF there is a swtich:
```bash
$ sf -h
Usage of sf:
  -csv
    	CSV output format
  -droid
    	DROID CSV output format
```
I'm very excited that you're playing with format reports again!!!

**Comment by ross-spencer** [comment]
I don't know what it was - SF had changed its output slightly, but give it a go now with the new commit, should be a-okay!

**Comment by richardlehane** [comment]
yes sorry - this bug was me, the basis field had a little update last year
(I wasn't expecting anyone to be foolhardy enough to try to parse it :))

**Comment by ross-spencer** [comment]
You know me Richard, I'm nothing but through in my foolhardiness!!! :laughing: 

(It was nice to go back into the code actually, I think it's pushed its way closer to the top of my TODO to do some spring cleaning here.)

**Comment by andreakb** [comment]
Thank you!! It works beautifully with the YAML sf export! However, when I tried with the siegfried droid export option, I get the same Unknown export error. My commands were: 

`sf -droid -hash sha1 /media/sf_Digital_Collections/ResurectionMen-Staging/ > resmen.csv`

and 

`python droidsqliteanalysis.py --export resmen.csv `

**Comment by ross-spencer** [comment]
Fixed now too @andreakb I must not have tested that much once I started separating the code out. SF just doesn't escape it's CSV fields, but that bit is only needed for the identification. I fix that here: https://github.com/exponential-decay/droid-siegfried-sqlite-analysis-engine/commit/94b98d6078620132a53a08fd87adacd84e129ba1

**Comment by ross-spencer** [comment]
While I've got your ear @andreakb how important do you think it is that this code be possible to download and install without dependencies? It doesn't seem to get much use, and for those that do use it, maybe it is better to be able to update dependencies dynamically? Also, lots of the code can be pulled apart into separate packages - last night's refactor overhauled the filename analysis component, so I'm going to stick that in a repo of its own today (keep this version going too) and then that can be run standalone.

**Comment by andreakb** [comment]
Ah interesting idea! I think the one dependency had to download was a python library (now of course I can't remember which one & it's not in my history!), I think if it's not too much more work on your end, and you have time for it, it may g some way to lower the barriers to using the analysis tool. I think, if you were wanting to do another roll out of the tool at some point, and introduce more archivists/digital collections types to the analysis tool, it could be something to add.
